#!/usr/bin/env python3
"""Regenerate data.js from all files in data/.

Bundles every file in data/ as a JSON string into window.CSVQUIZ_DATA so
premade quizzes work when index.html is opened from file://, where browsers
block fetch() of local files.

Usage: python build_data.py
"""
import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
OUT_FILE = os.path.join(os.path.dirname(__file__), 'data.js')

entries = []
for fname in sorted(os.listdir(DATA_DIR)):
    if not fname.endswith('.csv'):
        continue
    fpath = os.path.join(DATA_DIR, fname)
    with open(fpath, 'r', encoding='utf-8') as f:
        contents = f.read()
    entries.append(f'  {json.dumps(fname)}: {json.dumps(contents)}')

with open(OUT_FILE, 'w', encoding='utf-8') as out:
    out.write('// AUTO-GENERATED by build_data.py - do not edit by hand.\n')
    out.write('// Offline bundle of data/ so premade quizzes work from file://.\n')
    out.write('window.CSVQUIZ_DATA = {\n')
    out.write(',\n'.join(entries))
    out.write('\n};\n')

print(f'data.js written with {len(entries)} files.')
